### ISSUE TITLE
preemptible instances

### ISSUE THREAD

**Issue by thraxil** [appsembler/sultan#41]
I thought it used to do this... but currently, creating a new instance does not set it as preemptible and it will keep running indefinitely:

![screenshot-2021-02-24-153157](https://user-images.githubusercontent.com/7821/109024386-9b348280-76b5-11eb-9a79-333071f0103f.png)

We should default to preemptible instances so we don't keep paying for them if a developer forgets to shut theirs off (and to minimize its exposure to cryptominers, etc.)

**Comment by thraxil** [comment]
It's probably also worth thinking about the fact that at least from our perspective, the aspect of "preemptible" that we care about isn't that they are cheaper, but that they will automatically be shut off after a finite amount of time. With devstacks that users might spin up and forget about, that's really useful. Figuring out some other way to essentially automate "garbage collection", that would also be fine. Eg, a script that gets deployed to the server that initiates a `shutdown -h now` if it's seen that no one has accessed it in more than X hours. Or a Cloud Function that runs on a schedule and terminates any VMs more than X hours old that haven't been given a "persistent" label or something.

**Comment by ahmedaljazzar** [comment]
Solved in #44 and #43
