### ISSUE TITLE
Recommended machine size? 

### ISSUE THREAD

**Issue by briandant** [appsembler/sultan#5]
In the README, should we recommend a machine type and size?

**Comment by briandant** [comment]
I see now. I assumed that I would / could bring my own machine. Machine size is instead hard-coded. (Which is another question to ask, I suppose.)

**Comment by ahmedaljazzar** [comment]
This is a good question. You can change the machine type on [.config#32](https://github.com/appsembler/sultan/blob/master/.configs#L32). It's not hardcoded. The machine type is taken from edX platform recommendations for a better performance. However, we are going to change the machine kind to preemptive machines in the next version.

**Comment by briandant** [comment]
@ahmedaljazzar: Okay. I presume the machine type is documented in the wiki; I was using merely the getting started section of the README.

**Comment by ahmedaljazzar** [comment]
I added support for preemptible machine and updated the documentation accordingly regarding the recommended machine types.
